### PR TITLE
add @juliuste

### PR DESCRIPTION
**Pull request by juliuste**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
I will update the avatars :)

**Comment by juliuste** [comment]
> I will update the avatars :)

Bump (:

**Comment by MorrisJobke** [comment]
> Bump (:

https://github.com/okfde/codefor.de#update-avatars 😉

**Comment by MorrisJobke** [comment]
I found the issue. Should be fixed now ;)

**Comment by juliuste** [comment]
Thx (:

**Pull request merged**
