### PR TITLE
add Jan to Code for München team

### PR DESCRIPTION
**Pull request by jancborchardt**
Cheers! cc @digisus @morrisjobke :)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Ich werd mir mal angucken, was da kaputt gegangen ist.

**Comment by MorrisJobke** [comment]
fixed

**Comment by MorrisJobke** [comment]
@jancborchardt Keep in mind to also download your avatar (there is a download_avatar.py inside of the root folder) ;)

**Comment by MorrisJobke** [comment]
Fixed for you: 42957ac163057af940658aeeaae984be1c9671d7

**Comment by jancborchardt** [comment]
Thanks! :)

**Pull request merged**
