### PR TITLE
Add blog article "Senatsverwaltung zu Gast".

### PR DESCRIPTION
**Pull request by johnjohndoe**
@choefele @k-nut @tursics @MagdaN @sjockers Bitte Korrektur lesen und ggf. ergänzen.

### CODE REVIEW

**Comment by choefele** [comment]
Looks great – thanks. Perhaps mention the e-mail address for questions about FIS-Broker/licenses (fisbroker@senstadtum.berlin.de). I'm currently in contact with Renate Zweer to discuss the license for the 3D model of Berlin.

-Claus

**Comment by johnjohndoe** [comment]
Thanks. Actually she prefers her personalized address over the mentioned address (which will be rededicate for "first level support" usage). I plan to inform everybody via the mailing list as soon as the article is live.

**Comment by johnjohndoe** [comment]
@MorrisJobke @MagdaN 
Kann das bitte jemand mergen? Danke.

**Comment by johnjohndoe** [comment]
:+1: Danke

**Pull request merged**
