### PR TITLE
Updated installation instructions

### PR DESCRIPTION
**Pull request by keimlink**
Split the installation instructions into different sections. Added a section to
explain how to do installation just for the project using Bundler.

Also added instructions how to run jekyll if Bundler has been used to install
the gems.

### CODE REVIEW

**Comment by keimlink** [comment]
I would appreciate some feedback on this, especially because I'm not using Ruby every day.

**Comment by mattfullerton** [comment]
Would it be possible to reference GitHub's instructions too? https://help.github.com/articles/using-jekyll-with-pages

I'm not sure if its safe to make blanket statements about OS X... which version, etc.?

**Comment by keimlink** [comment]
I have no clue how Jekyll works or how to install it. The current README.md has very sparse instructions how to set up the project. I just wanted to help other people that have the same problems like me and share my experience. Of course I would be happy if other (OS X) users could test my instructions.

I added Bundler to the setup instructions because AFAIK it's the state-of-the-art-tool to install Ruby gems and because I don't wanted to clutter my system-wide Ruby installation with the gems needed for codefor.de.

**Comment by keimlink** [comment]
I don't understand why pull request #108 has been merged, which added rvm but didn't add a single line of documentation.

I tried to use rvm but I failed terribly. This is why I started using Bundler. Also because some friends with more Ruby experience told me it's the best tool to install and track Gems.

**Comment by mattfullerton** [comment]
Sorry that this took so long

**Comment by keimlink** [comment]
Thanks!

**Pull request merged**
